<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdAdvertise', 'doctrine');

/**
 * BaseAdAdvertise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $location
 * @property string $view_type
 * @property integer $amount
 * @property integer $width
 * @property integer $height
 * @property string $lang
 * @property boolean $is_active
 * @property Doctrine_Collection $AdvertiseImage
 * @property AdAdvertiseLocation $AdvertiseLocation
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method string              getLocation()          Returns the current record's "location" value
 * @method string              getViewType()          Returns the current record's "view_type" value
 * @method integer             getAmount()            Returns the current record's "amount" value
 * @method integer             getWidth()             Returns the current record's "width" value
 * @method integer             getHeight()            Returns the current record's "height" value
 * @method string              getLang()              Returns the current record's "lang" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getAdvertiseImage()    Returns the current record's "AdvertiseImage" collection
 * @method AdAdvertiseLocation getAdvertiseLocation() Returns the current record's "AdvertiseLocation" value
 * @method AdAdvertise         setName()              Sets the current record's "name" value
 * @method AdAdvertise         setDescription()       Sets the current record's "description" value
 * @method AdAdvertise         setLocation()          Sets the current record's "location" value
 * @method AdAdvertise         setViewType()          Sets the current record's "view_type" value
 * @method AdAdvertise         setAmount()            Sets the current record's "amount" value
 * @method AdAdvertise         setWidth()             Sets the current record's "width" value
 * @method AdAdvertise         setHeight()            Sets the current record's "height" value
 * @method AdAdvertise         setLang()              Sets the current record's "lang" value
 * @method AdAdvertise         setIsActive()          Sets the current record's "is_active" value
 * @method AdAdvertise         setAdvertiseImage()    Sets the current record's "AdvertiseImage" collection
 * @method AdAdvertise         setAdvertiseLocation() Sets the current record's "AdvertiseLocation" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdAdvertise extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_advertise');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên banner',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'comment' => 'Mô tả',
             'length' => 500,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Trang hiển thị',
             'length' => 255,
             ));
        $this->hasColumn('view_type', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Kiểu hiển thị S=Slide, F=Flash, I=Ảnh',
             'length' => 10,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Số lượng ảnh hiển thị',
             'default' => 0,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Chiều rộng',
             'default' => 0,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Chiều cao',
             'default' => 0,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0=chưa sử dụng, 1= sử dụng',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdAdvertiseImage as AdvertiseImage', array(
             'local' => 'id',
             'foreign' => 'advertise_id'));

        $this->hasOne('AdAdvertiseLocation as AdvertiseLocation', array(
             'local' => 'id',
             'foreign' => 'advertise_id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}