<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpMenu', 'doctrine');

/**
 * BaseVtpMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $image_path
 * @property boolean $is_active
 * @property string $lang
 * @property integer $parent_id
 * @property string $slug
 * @property string $link
 * @property integer $level
 * @property integer $priority
 * @property boolean $is_detail
 * @property integer $type
 * @property VtpMenu $VtpParentMenu
 * @property Doctrine_Collection $ParentMenu
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method clob                getDescription()   Returns the current record's "description" value
 * @method string              getImagePath()     Returns the current record's "image_path" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method string              getLang()          Returns the current record's "lang" value
 * @method integer             getParentId()      Returns the current record's "parent_id" value
 * @method string              getSlug()          Returns the current record's "slug" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method integer             getLevel()         Returns the current record's "level" value
 * @method integer             getPriority()      Returns the current record's "priority" value
 * @method boolean             getIsDetail()      Returns the current record's "is_detail" value
 * @method integer             getType()          Returns the current record's "type" value
 * @method VtpMenu             getVtpParentMenu() Returns the current record's "VtpParentMenu" value
 * @method Doctrine_Collection getParentMenu()    Returns the current record's "ParentMenu" collection
 * @method VtpMenu             setName()          Sets the current record's "name" value
 * @method VtpMenu             setDescription()   Sets the current record's "description" value
 * @method VtpMenu             setImagePath()     Sets the current record's "image_path" value
 * @method VtpMenu             setIsActive()      Sets the current record's "is_active" value
 * @method VtpMenu             setLang()          Sets the current record's "lang" value
 * @method VtpMenu             setParentId()      Sets the current record's "parent_id" value
 * @method VtpMenu             setSlug()          Sets the current record's "slug" value
 * @method VtpMenu             setLink()          Sets the current record's "link" value
 * @method VtpMenu             setLevel()         Sets the current record's "level" value
 * @method VtpMenu             setPriority()      Sets the current record's "priority" value
 * @method VtpMenu             setIsDetail()      Sets the current record's "is_detail" value
 * @method VtpMenu             setType()          Sets the current record's "type" value
 * @method VtpMenu             setVtpParentMenu() Sets the current record's "VtpParentMenu" value
 * @method VtpMenu             setParentMenu()    Sets the current record's "ParentMenu" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_menu');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên menu',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Mô tả menu',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'File ảnh đại diện menu',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Menu cấp cha',
             'length' => 5,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn của Menu (nếu có)',
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'phân cấp Menu',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('is_detail', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'có xem bài chi tiết hay không',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => '0-menu chính, 1-Menu footer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtpMenu as VtpParentMenu', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('VtpMenu as ParentMenu', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}