<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpProductImage', 'doctrine');

/**
 * BaseVtpProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_path
 * @property integer $product_id
 * @property string $extension
 * @property integer $priority
 * @property VtpProducts $VtpProductImage
 * 
 * @method string          getFilePath()        Returns the current record's "file_path" value
 * @method integer         getProductId()       Returns the current record's "product_id" value
 * @method string          getExtension()       Returns the current record's "extension" value
 * @method integer         getPriority()        Returns the current record's "priority" value
 * @method VtpProducts     getVtpProductImage() Returns the current record's "VtpProductImage" value
 * @method VtpProductImage setFilePath()        Sets the current record's "file_path" value
 * @method VtpProductImage setProductId()       Sets the current record's "product_id" value
 * @method VtpProductImage setExtension()       Sets the current record's "extension" value
 * @method VtpProductImage setPriority()        Sets the current record's "priority" value
 * @method VtpProductImage setVtpProductImage() Sets the current record's "VtpProductImage" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpProductImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_products_image');
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'sản phẩm thiết bị',
             ));
        $this->hasColumn('extension', 'string', 200, array(
             'type' => 'string',
             'comment' => 'phần mở rộng của file',
             'length' => 200,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtpProducts as VtpProductImage', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}