<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdPhoto', 'doctrine');

/**
 * BaseAdPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $file_path
 * @property integer $album_id
 * @property string $extension
 * @property integer $priority
 * @property boolean $is_active
 * @property boolean $is_default
 * @property AdAlbum $AdAlbumPhoto
 * 
 * @method string  getName()         Returns the current record's "name" value
 * @method string  getFilePath()     Returns the current record's "file_path" value
 * @method integer getAlbumId()      Returns the current record's "album_id" value
 * @method string  getExtension()    Returns the current record's "extension" value
 * @method integer getPriority()     Returns the current record's "priority" value
 * @method boolean getIsActive()     Returns the current record's "is_active" value
 * @method boolean getIsDefault()    Returns the current record's "is_default" value
 * @method AdAlbum getAdAlbumPhoto() Returns the current record's "AdAlbumPhoto" value
 * @method AdPhoto setName()         Sets the current record's "name" value
 * @method AdPhoto setFilePath()     Sets the current record's "file_path" value
 * @method AdPhoto setAlbumId()      Sets the current record's "album_id" value
 * @method AdPhoto setExtension()    Sets the current record's "extension" value
 * @method AdPhoto setPriority()     Sets the current record's "priority" value
 * @method AdPhoto setIsActive()     Sets the current record's "is_active" value
 * @method AdPhoto setIsDefault()    Sets the current record's "is_default" value
 * @method AdPhoto setAdAlbumPhoto() Sets the current record's "AdAlbumPhoto" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_album_photo');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên photo',
             'length' => 255,
             ));
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'banner quảng cáo',
             ));
        $this->hasColumn('extension', 'string', 200, array(
             'type' => 'string',
             'comment' => 'phần mở rộng của file',
             'length' => 200,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0=chưa sử dụng, 1= sử dụng',
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Ảnh đại diện cho Album',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdAlbum as AdAlbumPhoto', array(
             'local' => 'album_id',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}