<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdReportTotalRecord', 'doctrine');

/**
 * BaseAdReportTotalRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $total_record
 * @property timestamp $date_time
 * 
 * @method integer             getCategoryId()   Returns the current record's "category_id" value
 * @method integer             getTotalRecord()  Returns the current record's "total_record" value
 * @method timestamp           getDateTime()     Returns the current record's "date_time" value
 * @method AdReportTotalRecord setCategoryId()   Sets the current record's "category_id" value
 * @method AdReportTotalRecord setTotalRecord()  Sets the current record's "total_record" value
 * @method AdReportTotalRecord setDateTime()     Sets the current record's "date_time" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdReportTotalRecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_report_total_record');
        $this->hasColumn('category_id', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'chuyen muc thong ke',
             'length' => 5,
             ));
        $this->hasColumn('total_record', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'tong so ban ghi trong chuyen muc',
             'length' => 5,
             ));
        $this->hasColumn('date_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}