<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdCategoryPermission', 'doctrine');

/**
 * BaseAdCategoryPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $permission_id
 * @property Doctrine_Collection $CategoryPermission
 * 
 * @method integer              getCategoryId()         Returns the current record's "category_id" value
 * @method integer              getPermissionId()       Returns the current record's "permission_id" value
 * @method Doctrine_Collection  getCategoryPermission() Returns the current record's "CategoryPermission" collection
 * @method AdCategoryPermission setCategoryId()         Sets the current record's "category_id" value
 * @method AdCategoryPermission setPermissionId()       Sets the current record's "permission_id" value
 * @method AdCategoryPermission setCategoryPermission() Sets the current record's "CategoryPermission" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdCategoryPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_category_permission');
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Id của danh mục tin tức',
             'length' => 8,
             ));
        $this->hasColumn('permission_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Id quyền',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdCategory as CategoryPermission', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}