<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdHtml', 'doctrine');

/**
 * BaseAdHtml
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image_path
 * @property clob $content
 * @property boolean $is_active
 * @property string $lang
 * @property string $slug
 * @property string $prefix_path
 * 
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getImagePath()   Returns the current record's "image_path" value
 * @method clob    getContent()     Returns the current record's "content" value
 * @method boolean getIsActive()    Returns the current record's "is_active" value
 * @method string  getLang()        Returns the current record's "lang" value
 * @method string  getSlug()        Returns the current record's "slug" value
 * @method string  getPrefixPath()  Returns the current record's "prefix_path" value
 * @method AdHtml  setName()        Sets the current record's "name" value
 * @method AdHtml  setImagePath()   Sets the current record's "image_path" value
 * @method AdHtml  setContent()     Sets the current record's "content" value
 * @method AdHtml  setIsActive()    Sets the current record's "is_active" value
 * @method AdHtml  setLang()        Sets the current record's "lang" value
 * @method AdHtml  setSlug()        Sets the current record's "slug" value
 * @method AdHtml  setPrefixPath()  Sets the current record's "prefix_path" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdHtml extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_html');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên bài viết',
             'length' => 255,
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn ảnh đại diện',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung bài viết',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái duyệt bài viết',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('prefix_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn trang hiển thị vd: /gioi-thieu/:slug',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}