<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdProductCategory', 'doctrine');

/**
 * BaseAdProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $image_path
 * @property boolean $is_active
 * @property string $lang
 * @property integer $parent_id
 * @property string $slug
 * @property string $meta_keyword
 * @property string $meta_description
 * @property string $link
 * @property integer $level
 * @property integer $priority
 * 
 * @method string            getName()             Returns the current record's "name" value
 * @method clob              getDescription()      Returns the current record's "description" value
 * @method string            getImagePath()        Returns the current record's "image_path" value
 * @method boolean           getIsActive()         Returns the current record's "is_active" value
 * @method string            getLang()             Returns the current record's "lang" value
 * @method integer           getParentId()         Returns the current record's "parent_id" value
 * @method string            getSlug()             Returns the current record's "slug" value
 * @method string            getMetaKeyword()      Returns the current record's "meta_keyword" value
 * @method string            getMetaDescription()  Returns the current record's "meta_description" value
 * @method string            getLink()             Returns the current record's "link" value
 * @method integer           getLevel()            Returns the current record's "level" value
 * @method integer           getPriority()         Returns the current record's "priority" value
 * @method AdProductCategory setName()             Sets the current record's "name" value
 * @method AdProductCategory setDescription()      Sets the current record's "description" value
 * @method AdProductCategory setImagePath()        Sets the current record's "image_path" value
 * @method AdProductCategory setIsActive()         Sets the current record's "is_active" value
 * @method AdProductCategory setLang()             Sets the current record's "lang" value
 * @method AdProductCategory setParentId()         Sets the current record's "parent_id" value
 * @method AdProductCategory setSlug()             Sets the current record's "slug" value
 * @method AdProductCategory setMetaKeyword()      Sets the current record's "meta_keyword" value
 * @method AdProductCategory setMetaDescription()  Sets the current record's "meta_description" value
 * @method AdProductCategory setLink()             Sets the current record's "link" value
 * @method AdProductCategory setLevel()            Sets the current record's "level" value
 * @method AdProductCategory setPriority()         Sets the current record's "priority" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdProductCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_product_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên chuyên mục sản phẩm',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Mô tả chuyên mục',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'File ảnh đại diện chuyên mục',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('meta_keyword', 'string', 255, array(
             'type' => 'string',
             'comment' => 'keyword',
             'length' => 255,
             ));
        $this->hasColumn('meta_description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'meta description',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn của chuyên mục (nếu có)',
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'phân cấp chuyên mục',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}