<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdArticle', 'doctrine');

/**
 * BaseAdArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $alttitle
 * @property clob $header
 * @property clob $body
 * @property string $image_path
 * @property integer $attributes
 * @property integer $hit_count
 * @property integer $priority
 * @property timestamp $published_time
 * @property timestamp $expiredate_time
 * @property string $meta
 * @property string $keywords
 * @property string $author
 * @property clob $other_link
 * @property integer $is_active
 * @property boolean $is_hot
 * @property string $lang
 * @property string $slug
 * @property integer $category_id
 * @property AdCategory $AdArticleCategory
 * @property Doctrine_Collection $ArticlesRelated
 * @property Doctrine_Collection $RelatedArticles
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getAlttitle()          Returns the current record's "alttitle" value
 * @method clob                getHeader()            Returns the current record's "header" value
 * @method clob                getBody()              Returns the current record's "body" value
 * @method string              getImagePath()         Returns the current record's "image_path" value
 * @method integer             getAttributes()        Returns the current record's "attributes" value
 * @method integer             getHitCount()          Returns the current record's "hit_count" value
 * @method integer             getPriority()          Returns the current record's "priority" value
 * @method timestamp           getPublishedTime()     Returns the current record's "published_time" value
 * @method timestamp           getExpiredateTime()    Returns the current record's "expiredate_time" value
 * @method string              getMeta()              Returns the current record's "meta" value
 * @method string              getKeywords()          Returns the current record's "keywords" value
 * @method string              getAuthor()            Returns the current record's "author" value
 * @method clob                getOtherLink()         Returns the current record's "other_link" value
 * @method integer             getIsActive()          Returns the current record's "is_active" value
 * @method boolean             getIsHot()             Returns the current record's "is_hot" value
 * @method string              getLang()              Returns the current record's "lang" value
 * @method string              getSlug()              Returns the current record's "slug" value
 * @method integer             getCategoryId()        Returns the current record's "category_id" value
 * @method AdCategory          getAdArticleCategory() Returns the current record's "AdArticleCategory" value
 * @method Doctrine_Collection getArticlesRelated()   Returns the current record's "ArticlesRelated" collection
 * @method Doctrine_Collection getRelatedArticles()   Returns the current record's "RelatedArticles" collection
 * @method AdArticle           setTitle()             Sets the current record's "title" value
 * @method AdArticle           setAlttitle()          Sets the current record's "alttitle" value
 * @method AdArticle           setHeader()            Sets the current record's "header" value
 * @method AdArticle           setBody()              Sets the current record's "body" value
 * @method AdArticle           setImagePath()         Sets the current record's "image_path" value
 * @method AdArticle           setAttributes()        Sets the current record's "attributes" value
 * @method AdArticle           setHitCount()          Sets the current record's "hit_count" value
 * @method AdArticle           setPriority()          Sets the current record's "priority" value
 * @method AdArticle           setPublishedTime()     Sets the current record's "published_time" value
 * @method AdArticle           setExpiredateTime()    Sets the current record's "expiredate_time" value
 * @method AdArticle           setMeta()              Sets the current record's "meta" value
 * @method AdArticle           setKeywords()          Sets the current record's "keywords" value
 * @method AdArticle           setAuthor()            Sets the current record's "author" value
 * @method AdArticle           setOtherLink()         Sets the current record's "other_link" value
 * @method AdArticle           setIsActive()          Sets the current record's "is_active" value
 * @method AdArticle           setIsHot()             Sets the current record's "is_hot" value
 * @method AdArticle           setLang()              Sets the current record's "lang" value
 * @method AdArticle           setSlug()              Sets the current record's "slug" value
 * @method AdArticle           setCategoryId()        Sets the current record's "category_id" value
 * @method AdArticle           setAdArticleCategory() Sets the current record's "AdArticleCategory" value
 * @method AdArticle           setArticlesRelated()   Sets the current record's "ArticlesRelated" collection
 * @method AdArticle           setRelatedArticles()   Sets the current record's "RelatedArticles" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_article');
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tiêu đề bài viết',
             'length' => 512,
             ));
        $this->hasColumn('alttitle', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tiêu đề rút gọn',
             'length' => 255,
             ));
        $this->hasColumn('header', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Trích yếu',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung bài viết trên web',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn ảnh đại diện',
             'length' => 255,
             ));
        $this->hasColumn('attributes', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Thuộc tính của bài viết: khuyến mại, ',
             'length' => 8,
             ));
        $this->hasColumn('hit_count', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Số lượt truy cập',
             'length' => 8,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('published_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Thời gian xuất bản',
             'length' => 25,
             ));
        $this->hasColumn('expiredate_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'comment' => 'Thời gian kết thúc bản tin',
             'length' => 25,
             ));
        $this->hasColumn('meta', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nội dung meta',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nội dung keywords',
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tác giả',
             'length' => 255,
             ));
        $this->hasColumn('other_link', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Các link liên quan',
             ));
        $this->hasColumn('is_active', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => 'Trạng thái hiển thị (-1: Bản nháp, 0- Chờ duyệt, 1- Đã duyệt, 2- Đã đăng)',
             'length' => 5,
             ));
        $this->hasColumn('is_hot', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Hiển thị trên trang chủ (0- ko hiển thị, 1- hiển thị)',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'comment' => 'Id của danh mục tin tức',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdCategory as AdArticleCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('AdArticle as ArticlesRelated', array(
             'refClass' => 'AdArticlesRelated',
             'local' => 'id',
             'foreign' => 'article_id'));

        $this->hasMany('AdArticle as RelatedArticles', array(
             'refClass' => 'AdArticlesRelated',
             'local' => 'article_id',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}