<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdProduct', 'doctrine');

/**
 * BaseAdProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property clob $content
 * @property string $image_path
 * @property boolean $is_active
 * @property boolean $is_hot
 * @property string $lang
 * @property integer $category_id
 * @property string $slug
 * @property string $meta_keyword
 * @property string $meta_description
 * @property int $price
 * 
 * @method string    getName()             Returns the current record's "name" value
 * @method clob      getDescription()      Returns the current record's "description" value
 * @method clob      getContent()          Returns the current record's "content" value
 * @method string    getImagePath()        Returns the current record's "image_path" value
 * @method boolean   getIsActive()         Returns the current record's "is_active" value
 * @method boolean   getIsHot()            Returns the current record's "is_hot" value
 * @method string    getLang()             Returns the current record's "lang" value
 * @method integer   getCategoryId()       Returns the current record's "category_id" value
 * @method string    getSlug()             Returns the current record's "slug" value
 * @method string    getMetaKeyword()      Returns the current record's "meta_keyword" value
 * @method string    getMetaDescription()  Returns the current record's "meta_description" value
 * @method int       getPrice()            Returns the current record's "price" value
 * @method AdProduct setName()             Sets the current record's "name" value
 * @method AdProduct setDescription()      Sets the current record's "description" value
 * @method AdProduct setContent()          Sets the current record's "content" value
 * @method AdProduct setImagePath()        Sets the current record's "image_path" value
 * @method AdProduct setIsActive()         Sets the current record's "is_active" value
 * @method AdProduct setIsHot()            Sets the current record's "is_hot" value
 * @method AdProduct setLang()             Sets the current record's "lang" value
 * @method AdProduct setCategoryId()       Sets the current record's "category_id" value
 * @method AdProduct setSlug()             Sets the current record's "slug" value
 * @method AdProduct setMetaKeyword()      Sets the current record's "meta_keyword" value
 * @method AdProduct setMetaDescription()  Sets the current record's "meta_description" value
 * @method AdProduct setPrice()            Sets the current record's "price" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_product');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên chuyên mục sản phẩm',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Mô tả chuyên mục',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung sản phẩm',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'File ảnh đại diện',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('is_hot', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('category_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('meta_keyword', 'string', 255, array(
             'type' => 'string',
             'comment' => 'keyword',
             'length' => 255,
             ));
        $this->hasColumn('meta_description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'meta description',
             'length' => 255,
             ));
        $this->hasColumn('price', 'int', 10, array(
             'type' => 'int',
             'comment' => 'giá',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}