<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdPersonal', 'doctrine');

/**
 * BaseAdPersonal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $full_name
 * @property timestamp $birthday
 * @property string $sex
 * @property string $phone_number
 * @property string $email
 * @property string $address
 * @property string $introduction
 * 
 * @method string     getFullName()     Returns the current record's "full_name" value
 * @method timestamp  getBirthday()     Returns the current record's "birthday" value
 * @method string     getSex()          Returns the current record's "sex" value
 * @method string     getPhoneNumber()  Returns the current record's "phone_number" value
 * @method string     getEmail()        Returns the current record's "email" value
 * @method string     getAddress()      Returns the current record's "address" value
 * @method string     getIntroduction() Returns the current record's "introduction" value
 * @method AdPersonal setFullName()     Sets the current record's "full_name" value
 * @method AdPersonal setBirthday()     Sets the current record's "birthday" value
 * @method AdPersonal setSex()          Sets the current record's "sex" value
 * @method AdPersonal setPhoneNumber()  Sets the current record's "phone_number" value
 * @method AdPersonal setEmail()        Sets the current record's "email" value
 * @method AdPersonal setAddress()      Sets the current record's "address" value
 * @method AdPersonal setIntroduction() Sets the current record's "introduction" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdPersonal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_personal');
        $this->hasColumn('full_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Ho ten nguoi gop y',
             'length' => 255,
             ));
        $this->hasColumn('birthday', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => false,
             'comment' => 'Ngày sinh',
             'length' => 25,
             ));
        $this->hasColumn('sex', 'string', 25, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Giới tính',
             'length' => 25,
             ));
        $this->hasColumn('phone_number', 'string', 25, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('introduction', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}