<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdReportHicounter', 'doctrine');

/**
 * BaseAdReportHicounter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $hitcounter
 * 
 * @method integer           getCategoryId()  Returns the current record's "category_id" value
 * @method integer           getHitcounter()  Returns the current record's "hitcounter" value
 * @method AdReportHicounter setCategoryId()  Sets the current record's "category_id" value
 * @method AdReportHicounter setHitcounter()  Sets the current record's "hitcounter" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdReportHicounter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_report_hitcounter');
        $this->hasColumn('category_id', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'chuyen muc thong ke',
             'length' => 5,
             ));
        $this->hasColumn('hitcounter', 'integer', 5, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Tong so luot xem',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}