<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdChainImage', 'doctrine');

/**
 * BaseAdChainImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_path
 * @property string $extension
 * @property integer $priority
 * @property integer $product
 * @property boolean $is_active
 * @property string $lang
 * 
 * @method string       getFilePath()  Returns the current record's "file_path" value
 * @method string       getExtension() Returns the current record's "extension" value
 * @method integer      getPriority()  Returns the current record's "priority" value
 * @method integer      getProduct()   Returns the current record's "product" value
 * @method boolean      getIsActive()  Returns the current record's "is_active" value
 * @method string       getLang()      Returns the current record's "lang" value
 * @method AdChainImage setFilePath()  Sets the current record's "file_path" value
 * @method AdChainImage setExtension() Sets the current record's "extension" value
 * @method AdChainImage setPriority()  Sets the current record's "priority" value
 * @method AdChainImage setProduct()   Sets the current record's "product" value
 * @method AdChainImage setIsActive()  Sets the current record's "is_active" value
 * @method AdChainImage setLang()      Sets the current record's "lang" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdChainImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_chain_image');
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('extension', 'string', 200, array(
             'type' => 'string',
             'comment' => 'phần mở rộng của file',
             'length' => 200,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('product', 'integer', 15, array(
             'type' => 'integer',
             'comment' => 'id product',
             'length' => 15,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             'comment' => 'Trạng thái',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}