<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdActivity', 'doctrine');

/**
 * BaseAdActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $image
 * @property integer $priority
 * @property integer $type
 * @property boolean $is_active
 * 
 * @method string     getName()        Returns the current record's "name" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method string     getImage()       Returns the current record's "image" value
 * @method integer    getPriority()    Returns the current record's "priority" value
 * @method integer    getType()        Returns the current record's "type" value
 * @method boolean    getIsActive()    Returns the current record's "is_active" value
 * @method AdActivity setName()        Sets the current record's "name" value
 * @method AdActivity setDescription() Sets the current record's "description" value
 * @method AdActivity setImage()       Sets the current record's "image" value
 * @method AdActivity setPriority()    Sets the current record's "priority" value
 * @method AdActivity setType()        Sets the current record's "type" value
 * @method AdActivity setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_activity');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên giảng viên',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'mô tả',
             'length' => 1000,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'ảnh đại diện',
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('type', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Loại chuyên mục',
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             'comment' => 'Trạng thái',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}