<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdArticlesComment', 'doctrine');

/**
 * BaseAdArticlesComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $fullname
 * @property string $email
 * @property string $content
 * @property boolean $is_active
 * 
 * @method integer           getArticleId()  Returns the current record's "article_id" value
 * @method string            getFullname()   Returns the current record's "fullname" value
 * @method string            getEmail()      Returns the current record's "email" value
 * @method string            getContent()    Returns the current record's "content" value
 * @method boolean           getIsActive()   Returns the current record's "is_active" value
 * @method AdArticlesComment setArticleId()  Sets the current record's "article_id" value
 * @method AdArticlesComment setFullname()   Sets the current record's "fullname" value
 * @method AdArticlesComment setEmail()      Sets the current record's "email" value
 * @method AdArticlesComment setContent()    Sets the current record's "content" value
 * @method AdArticlesComment setIsActive()   Sets the current record's "is_active" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdArticlesComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_article_comment');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Id của bài tin tức',
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'comment' => 'ho ten',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Email',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'comment' => 'Noi dung comment',
             'length' => 1000,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái duyệt bài viết',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}