<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpCategory', 'doctrine');

/**
 * BaseVtpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $image_path
 * @property boolean $is_active
 * @property string $lang
 * @property integer $parent_id
 * @property string $slug
 * @property string $link
 * @property integer $level
 * @property integer $priority
 * @property string $type
 * @property boolean $is_detail
 * @property integer $portal_id
 * @property VtpCategory $VtpParentCategory
 * @property Doctrine_Collection $ParentCategory
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method clob                getDescription()       Returns the current record's "description" value
 * @method string              getImagePath()         Returns the current record's "image_path" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method string              getLang()              Returns the current record's "lang" value
 * @method integer             getParentId()          Returns the current record's "parent_id" value
 * @method string              getSlug()              Returns the current record's "slug" value
 * @method string              getLink()              Returns the current record's "link" value
 * @method integer             getLevel()             Returns the current record's "level" value
 * @method integer             getPriority()          Returns the current record's "priority" value
 * @method string              getType()              Returns the current record's "type" value
 * @method boolean             getIsDetail()          Returns the current record's "is_detail" value
 * @method integer             getPortalId()          Returns the current record's "portal_id" value
 * @method VtpCategory         getVtpParentCategory() Returns the current record's "VtpParentCategory" value
 * @method Doctrine_Collection getParentCategory()    Returns the current record's "ParentCategory" collection
 * @method VtpCategory         setName()              Sets the current record's "name" value
 * @method VtpCategory         setDescription()       Sets the current record's "description" value
 * @method VtpCategory         setImagePath()         Sets the current record's "image_path" value
 * @method VtpCategory         setIsActive()          Sets the current record's "is_active" value
 * @method VtpCategory         setLang()              Sets the current record's "lang" value
 * @method VtpCategory         setParentId()          Sets the current record's "parent_id" value
 * @method VtpCategory         setSlug()              Sets the current record's "slug" value
 * @method VtpCategory         setLink()              Sets the current record's "link" value
 * @method VtpCategory         setLevel()             Sets the current record's "level" value
 * @method VtpCategory         setPriority()          Sets the current record's "priority" value
 * @method VtpCategory         setType()              Sets the current record's "type" value
 * @method VtpCategory         setIsDetail()          Sets the current record's "is_detail" value
 * @method VtpCategory         setPortalId()          Sets the current record's "portal_id" value
 * @method VtpCategory         setVtpParentCategory() Sets the current record's "VtpParentCategory" value
 * @method VtpCategory         setParentCategory()    Sets the current record's "ParentCategory" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên chuyên mục',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Mô tả chuyên mục',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'File ảnh đại diện chuyên mục',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn của chuyên mục (nếu có)',
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'phân cấp chuyên mục',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'comment' => 'N=Tin tức, S=Dịch vụ',
             'length' => 20,
             ));
        $this->hasColumn('is_detail', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'có xem bài chi tiết hay không',
             ));
        $this->hasColumn('portal_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Portal cần hiển thị nội dung, được quy ước trong file cấu hình (Khách hàng cá nhân / Khách hàng doanh nghiệp)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VtpCategory as VtpParentCategory', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('VtpCategory as ParentCategory', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}