<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdSeo', 'doctrine');

/**
 * BaseAdSeo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $keyword
 * @property string $image
 * 
 * @method string getTitle()       Returns the current record's "title" value
 * @method string getDescription() Returns the current record's "description" value
 * @method string getKeyword()     Returns the current record's "keyword" value
 * @method string getImage()       Returns the current record's "image" value
 * @method AdSeo  setTitle()       Sets the current record's "title" value
 * @method AdSeo  setDescription() Sets the current record's "description" value
 * @method AdSeo  setKeyword()     Sets the current record's "keyword" value
 * @method AdSeo  setImage()       Sets the current record's "image" value
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdSeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_seo');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tiêu đề',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('keyword', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Ảnh khi share lên FB',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}