<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdConfig', 'doctrine');

/**
 * BaseAdConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $config_key
 * @property string $config_val
 * @property boolean $is_active
 * @property string $lang
 * 
 * @method string   getConfigKey()  Returns the current record's "config_key" value
 * @method string   getConfigVal()  Returns the current record's "config_val" value
 * @method boolean  getIsActive()   Returns the current record's "is_active" value
 * @method string   getLang()       Returns the current record's "lang" value
 * @method AdConfig setConfigKey()  Sets the current record's "config_key" value
 * @method AdConfig setConfigVal()  Sets the current record's "config_val" value
 * @method AdConfig setIsActive()   Sets the current record's "is_active" value
 * @method AdConfig setLang()       Sets the current record's "lang" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_config');
        $this->hasColumn('config_key', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'config_key',
             'length' => 255,
             ));
        $this->hasColumn('config_val', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'config_val',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             'comment' => 'Trạng thái',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}