<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdManageFile', 'doctrine');

/**
 * BaseAdManageFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $short_url
 * @property clob $description
 * @property integer $type
 * @property integer $duration
 * @property integer $position
 * @property integer $type_product
 * 
 * @method integer      getArticleId()    Returns the current record's "article_id" value
 * @method string       getShortUrl()     Returns the current record's "short_url" value
 * @method clob         getDescription()  Returns the current record's "description" value
 * @method integer      getType()         Returns the current record's "type" value
 * @method integer      getDuration()     Returns the current record's "duration" value
 * @method integer      getPosition()     Returns the current record's "position" value
 * @method integer      getTypeProduct()  Returns the current record's "type_product" value
 * @method AdManageFile setArticleId()    Sets the current record's "article_id" value
 * @method AdManageFile setShortUrl()     Sets the current record's "short_url" value
 * @method AdManageFile setDescription()  Sets the current record's "description" value
 * @method AdManageFile setType()         Sets the current record's "type" value
 * @method AdManageFile setDuration()     Sets the current record's "duration" value
 * @method AdManageFile setPosition()     Sets the current record's "position" value
 * @method AdManageFile setTypeProduct()  Sets the current record's "type_product" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdManageFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_manage_file');
        $this->hasColumn('article_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'id tin tuc',
             'length' => 8,
             ));
        $this->hasColumn('short_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'media/2014/07/17/test.jpg',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'comment' => '1: image, 2: audio, 3 video',
             'length' => 2,
             ));
        $this->hasColumn('duration', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'vi tri anh, video',
             'length' => 4,
             ));
        $this->hasColumn('type_product', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'anh phan he',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}