<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdDocument', 'doctrine');

/**
 * BaseAdDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $file_path
 * @property string $extension
 * @property string $document_number
 * @property timestamp $document_date
 * @property integer $priority
 * @property integer $category_id
 * @property boolean $is_home
 * @property boolean $is_active
 * @property AdDocumentCategory $AdDocCategory
 * 
 * @method string             getName()            Returns the current record's "name" value
 * @method string             getDescription()     Returns the current record's "description" value
 * @method string             getFilePath()        Returns the current record's "file_path" value
 * @method string             getExtension()       Returns the current record's "extension" value
 * @method string             getDocumentNumber()  Returns the current record's "document_number" value
 * @method timestamp          getDocumentDate()    Returns the current record's "document_date" value
 * @method integer            getPriority()        Returns the current record's "priority" value
 * @method integer            getCategoryId()      Returns the current record's "category_id" value
 * @method boolean            getIsHome()          Returns the current record's "is_home" value
 * @method boolean            getIsActive()        Returns the current record's "is_active" value
 * @method AdDocumentCategory getAdDocCategory()   Returns the current record's "AdDocCategory" value
 * @method AdDocument         setName()            Sets the current record's "name" value
 * @method AdDocument         setDescription()     Sets the current record's "description" value
 * @method AdDocument         setFilePath()        Sets the current record's "file_path" value
 * @method AdDocument         setExtension()       Sets the current record's "extension" value
 * @method AdDocument         setDocumentNumber()  Sets the current record's "document_number" value
 * @method AdDocument         setDocumentDate()    Sets the current record's "document_date" value
 * @method AdDocument         setPriority()        Sets the current record's "priority" value
 * @method AdDocument         setCategoryId()      Sets the current record's "category_id" value
 * @method AdDocument         setIsHome()          Sets the current record's "is_home" value
 * @method AdDocument         setIsActive()        Sets the current record's "is_active" value
 * @method AdDocument         setAdDocCategory()   Sets the current record's "AdDocCategory" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_document');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Ho ten nguoi gop y',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('extension', 'string', 25, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('document_number', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('document_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('is_home', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Hiển thị trang chủ (0: không hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: Chưa kích hoạt, 1: đã kích hoạt)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdDocumentCategory as AdDocCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}