<?php

/**
 * PluginVtFAQsTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVtFAQsTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginVtFAQsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginVtFAQs');
  }

  /**
   * Lay tat ca du lieu cua bang vt_faq sap xep theo created_at DESC
   * @return string
   */
  public function getFAQsQuery()
  {
    $query = $this->createQuery('j')
        ->orderBy('created_at DESC,id DESC');
    return $query;
  }

  /**
   * Lay tat ca du lieu cua bang vt_faq sap xep theo id, created_at DESC
   * @return string
   */
  public function getActiveFAQs()
  {
    $query = $this->createQuery('j')
        ->where('is_active = 1');
    return $query;
  }

  /**
   * tra ve truy van lay danh sach cau hoi
   * @return string
   */
  public function getListFaqsQuery()
  {
    $query = $this->getActiveFAQs()
        ->orderBy('priority DESC,id DESC');
    return $query;

  }

  /**
   * Lay danh sách 5 cau hoi cung loai
   * @param type $param
   * @return object
   */
  public function getListOtherFAQs($id, $created_at, $limit)
  {
    $result = $this->getActiveFAQs()
        ->andWhere('id !=?', $id)
        ->andWhere('created_at <= ?', $created_at)
        ->orderBy('id DESC')
        ->limit($limit)
        ->execute();
    return $result;
  }

  /**
   * tra ve 1 cau lenh truy van lay ra ngay tao theo id
   * @param type $id
   * @return 1 cau truy van
   */
  public function getCreatedAtById($id)
  {
    $q = $this->createQuery('j')
        ->select('j.created_at')
        ->where('j.id = ?', $id)
        ->execute();
    return $q;
  }

  /**
   * hien thi chi tiet 1 cau hoi
   * @param type $id
   * @nhungnth12
   * @return object
   */
  public function getFaqById($id)
  {
    $result = $this->getListFaqsQuery()
        ->andWhere('id = ?', $id)
        ->fetchOne();
    ;
    return $result;
  }
}