<?php

/**
 * AdActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdActivity');
    }
}