<?php

/**
 * AdActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdActivity');
    }

    public static function getAllValues($type, $limit = 10)
    {
        return AdActivityTable::getInstance()->createQuery()
            ->where('is_active=1')
            ->andWhere('type=?',$type)
            ->orderBy('priority desc')
            ->limit($limit)
            ->fetchArray();
    }
}