<?php

/**
 * AdArticlesCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdArticlesCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdArticlesCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdArticlesComment');
    }
}