<?php

/**
 * AdArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdArticle extends BaseAdArticle
{
    public function getStatusName(){
        $nameArr = array(
            -1=>'Bản nháp',
            0=>'Đợi duyệt',
            1=>'Đã duyệt',
            2=>'Đã đăng'
        );
        if($this->getIsActive()!=null){
            return $nameArr[$this->getIsActive()];
        }
        return false;

    }
}