<?php

/**
 * AdArticlesRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdArticlesRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdArticlesRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdArticlesRelated');
    }

    public static function deleteArticleRelated($article)
    {
        $query=  AdArticlesRelatedTable::getInstance()->createQuery()
            ->delete()
            ->where('article_id=?',$article);
        return $query->execute();
    }

    public static function getArticleRelated($articleId){
        $query=  AdArticlesRelatedTable::getInstance()->createQuery()
            ->select('related_article_id')
            ->where('article_id=?',$articleId);
        $listArticle=$query->execute();
        $strItem='';
        foreach ($listArticle as $item){
            $strItem .=$item->related_article_id .',';
        }
        if ($strItem!=''){
            if(VtHelper::endsWith($strItem,',')){
                $strItem= substr($strItem, 0 ,strlen($strItem)-1);
            }
        }
        return $strItem;
    }
}