<?php

/**
 * AdCategoryPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdCategoryPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdCategoryPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdCategoryPermission');
    }

    public static function deletePermissionByCategory($categoryid)
    {
        $query = AdCategoryPermissionTable::getInstance()->createQuery()
            ->delete()
            ->where('category_id=?', $categoryid);
        return $query->execute();
    }

    public static function getPermissionByCategory($categoryid)
    {
        $query = AdCategoryPermissionTable::getInstance()->createQuery()
            ->select('permission_id')
            ->where('category_id=?', $categoryid);
        return $query->execute();
    }

    public static function getCatgoryIdByPermission($permissionId)
    {
        $query = AdCategoryPermissionTable::getInstance()->createQuery()
            ->select('category_id')
            ->whereIn('permission_id', explode(',', $permissionId));
        $listCat = $query->execute();
        $strCat = "";
        foreach ($listCat as $cat) {
            $strCat .= $cat->category_id . ',';
        }
        if ($strCat != '') {
            if (VtHelper::endsWith($strCat, ",")) {
                $strCat = substr($strCat, 0, strlen($strCat) - 1);
            }
        }
        return $strCat;
    }
    //Lay danh sach permission cua user
    public static function getPermissionByUserId($userId){
        $result = sfGuardUserPermissionTable::getInstance()->createQuery()
            ->select('permission_id')
            ->where('user_id=?',$userId)
            ->fetchArray();
        $arrPer = array();
        if(!empty($result)){
            foreach($result as $value){
                array_push($arrPer, $value['permission_id']);
            }
        }
        return $arrPer;
    }
    //Lay danh sach category theo mang permission truyen vao
    public static function getCatgoryIdByArrPermission($arrPermission)
    {
        $result = AdCategoryPermissionTable::getInstance()->createQuery()
            ->select('cp.category_id')
            ->from('AdCategoryPermission cp')
            ->leftJoin('cp.CategoryPermission c ON c.id=cp.category_id')
            ->whereIn('permission_id', $arrPermission)
            ->andWhere('c.lang=?', sfContext::getInstance()->getUser()->getCulture())

            ->fetchArray();
        $arrCat = array();
        if(!empty($result)){
            foreach($result as $value){
                array_push($arrCat, $value['category_id']);
            }
        }
        return $arrCat;

    }

    //Kiem tra quyen user thao tac danh muc
    public static function checkPermissionCategoryUser($userId, $categoryId, $type){
        $arrPer = AdCategoryPermissionTable::getPermissionByUserId($userId);
        $arrCat=AdCategoryPermissionTable::getCatgoryIdByArrPermission($arrPer, $type);
        if(in_array($categoryId, $arrCat)){
            return true;
        }
        return false;
    }
}