<?php

/**
 * AdCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdCategory extends BaseAdCategory
{
    public function getNewsByCategory(){
        return AdArticleTable::getListArticle($this->getId(),3)->fetchArray();
    }

    public function getChildCategory(){
        return AdCategoryTable::getChildCategory($this->getId(),3)->fetchArray();
    }
}