<?php

/**
 * AdChainImageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdChainImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdChainImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdChainImage');
    }

    public function getAllChainImage($chainId)
    {
        if ($chainId) {
            $query = $this->createQuery()
                ->andWhere('is_active=1')
                ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
                ->andWhere('product=?', $chainId)
                ->fetchArray();
            if (!empty($query)) {
                return $query;
            }
        }
        return false;
    }
}