<?php

/**
 * AdConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdConfig');
    }
}