<?php

/**
 * AdContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdContact');
    }

	public  static  function getContact(){
	    return AdContactTable::getInstance()->createQuery()
	        ->select()
	        ->fetchOne();
	}
}