<?php

/**
 * AdCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdComment');
    }


}