<?php

/**
 * AdDocumentCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdDocumentCategory extends BaseAdDocumentCategory
{
    public function getDocumentByCatId(){
        return AdDocumentTable::getDocumentByCatId($this->getId(), 5)->fetchArray();
    }
}