<?php

/**
 * AdDocumentDownloadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDocumentDownloadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDocumentDownloadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDocumentDownload');
    }
}