<?php

/**
 * AdDocumentCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdDocumentCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdDocumentCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdDocumentCategory');
    }

    public static function getCategoryDocumentById($id)
    {
        $query = AdDocumentCategoryTable::getInstance()->createQuery()
            ->Where('id=?', $id);
        return $query->fetchOne();
    }

    public static function getCategoryDocumentBySlug($slug)
    {
        $query = AdDocumentCategoryTable::getInstance()->createQuery()
            ->Where('slug=?', $slug);
        return $query->fetchOne();
    }

    //lay danh sach chuyen muc tai lieu hien thi trang chu
    public static function getCategoryDocumentHot($limit=null)
    {
        $query = AdDocumentCategoryTable::getInstance()->createQuery()
            ->select('name')
            ->Where('is_active=?', VtCommonEnum::NUMBER_ONE)
            ->andWhere('is_home=?', VtCommonEnum::NUMBER_ONE);
        if($limit){
            $query->limit($limit);
        }
        return $query;
    }
}