<?php

/**
 * AdFeedBackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdFeedBackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdFeedBackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdFeedBack');
    }
}