<?php

/**
 * AdGiangVienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdGiangVienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdGiangVienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdGiangVien');
    }
}