<?php

/**
 * AdHocVienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdHocVienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdHocVienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdHocVien');
    }
}