<?php

/**
 * AdHocVienTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdHocVienTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdHocVienTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdHocVien');
    }

    public static function getAllStudent($limit=13)
    {
        return AdHocVienTable::getInstance()->createQuery()
            ->where('is_active=1')
            ->orderBy('priority desc')
            ->limit($limit)
            ->fetchArray();
    }
}