<?php

/**
 * AdLinkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdLink');
    }

    public static function getLink($type = false)
    {
        $q = AdLinkTable::getInstance()->createQuery();
        if ($type) {
            $q->where('type=?', $type);
        }
        $query = $q->andWhere('is_active=1')
            ->orderBy('priority asc')
            ->fetchArray();
        return $query;
    }
}