<?php

/**
 * AdManageFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdManageFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdManageFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdManageFile');
    }
}