<?php

/**
 * AdNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdNews');
    }
}