<?php

/**
 * AdProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdProduct');
    }
}