<?php

/**
 * AdProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdProductCategory');
    }
}