<?php

/**
 * AdReportHicounterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdReportHicounterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdReportHicounterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdReportHicounter');
    }

    public static function getReport($catId){
        $q= AdReportHicounterTable::getInstance()->createQuery();
        if($catId!=''){
            $q->andWhere('(category_id=? or parent_id=?)',array($catId,$catId));
        }else{
            $q->andWhere('parent_id=0');
        }
        return  $q->fetchArray();
    }

}