<?php

/**
 * AdSeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdSeoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdSeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdSeo');
    }
}