<?php

/**
 * AdYoutubeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdYoutubeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdYoutubeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdYoutube');
    }


    public function getListSqlVideoYT($limit, $page)
    {
        $query = $this->createQuery()
            ->where('is_active=?', VtCommonEnum::NUMBER_ONE)
            ->orderBy('updated_at desc, priority asc');

        $pager = new sfDoctrinePager('AdYoutube', $limit);
        $pager->setQuery($query);
        $pager->setPage($page);
        $pager->init();
        return $pager;
    }

    public function getVideoYTBySlug($slug)
    {
        $query = $this->createQuery()
            ->where('is_active=?', VtCommonEnum::NUMBER_ONE)
            ->andWhere('id=?', $slug)
            ->fetchArray();
        if (!empty($query)) {
            return $query[0];
        }
        return false;
    }
}