<?php

/**
 * AdYoutubeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdYoutubeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdYoutubeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdYoutube');
    }
}