<?php

/**
 * ParameterCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ParameterCategory extends BaseParameterCategory
{
    public function getParamAttr()
    {
        $listParamAttr = ParameterTable::getInstance()->createQuery()->andWhere('cat_id=?', $this->getId())->fetchArray();
        if (!empty($listParamAttr)) {
            return $listParamAttr;
        }
        return false;
    }
}