<?php

/**
 * SendMailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SendMailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SendMailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SendMail');
    }
}