<?php

/**
 * VtpCategoryPermissionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtpCategoryPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtpCategoryPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtpCategoryPermission');
    }

    public static function deletePermissionByCategory($categoryid)
    {
        $query = VtpCategoryPermissionTable::getInstance()->createQuery()
            ->delete()
            ->where('category_id=?', $categoryid);
        return $query->execute();
    }

    public static function getPermissionByCategory($categoryid)
    {
        $query = VtpCategoryPermissionTable::getInstance()->createQuery()
            ->select('permission_id')
            ->where('category_id=?', $categoryid);
        return $query->execute();
    }

    public static function getCatgoryIdByPermission($permissionId)
    {
        $query = VtpCategoryPermissionTable::getInstance()->createQuery()
            ->select('category_id')
            ->whereIn('permission_id', explode(',', $permissionId));
        $listCat = $query->execute();
        $strCat = "";
        foreach ($listCat as $cat) {
            $strCat .= $cat->category_id . ',';
        }
        if ($strCat != '') {
            if (VtHelper::endsWith($strCat, ",")) {
                $strCat = substr($strCat, 0, strlen($strCat) - 1);
            }
        }
        return $strCat;
    }
    //Lay danh sach permission cua user
    public static function getPermissionByUserId($userId){
        $result = sfGuardUserPermissionTable::getInstance()->createQuery()
                ->select('permission_id')
                ->where('user_id=?',$userId)
                ->fetchArray();
        $arrPer = array();
        if(!empty($result)){
            foreach($result as $value){
                array_push($arrPer, $value['permission_id']);
            }
        }
        return $arrPer;
    }
    //Lay danh sach category theo mang permission truyen vao
    public static function getCatgoryIdByArrPermission($arrPermission, $type)
    {
        $result = VtpCategoryPermissionTable::getInstance()->createQuery()
            ->select('cp.category_id')
            ->from('VtpCategoryPermission cp')
            ->leftJoin('cp.CategoryPermission c ON c.id=cp.category_id')
            ->whereIn('permission_id', $arrPermission)
            ->andWhere('c.lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->andWhere('type=?',  $type)
            ->fetchArray();
        $arrCat = array();
        if(!empty($result)){
            foreach($result as $value){
                array_push($arrCat, $value['category_id']);
            }
        }
        return $arrCat;
    
    }
   
//    //Lay danh sach category theo quyen cua nguoi dung
//    public static function getCategoryIdByUserId($userId){
//        $arrPermisstion = self::getPermissionByUserId($userId);
//        $arrCat = array();
//        if(count($arrPermisstion>0)){
//            foreach($arrPermisstion as $value){
//                $result =  VtpCategoryPermissionTable::getInstance()->createQuery()
//                        ->select('category_id')
//                        ->where('permission_id=?',$value)
//                        ->fetchArray();
//                if(count($result>0)){
//                    foreach($result as $cat){
//                        array_push($arrCat, $cat);
//                    }
//                }
//            }
//        }
//        return $arrCat;
//    }
    //Kiem tra quyen user thao tac danh muc
    public static function checkPermissionCategoryUser($userId, $categoryId, $type){
        $arrPer = VtpCategoryPermissionTable::getPermissionByUserId($userId);
        $arrCat=VtpCategoryPermissionTable::getCatgoryIdByArrPermission($arrPer, $type);
        if(in_array($categoryId, $arrCat)){
            return true;
        }
        return false;
    }
}