<?php

/**
 * VtpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VtpCategory extends BaseVtpCategory
{
//    public function getListChildByParetId()
//    {
//        return VtpCategoryTable::getInstance()->getActiveCategoryWithParentIdQueryNew($this->getId());
//    }

    public function getListChildByParetId()
    {
        return VtpCategoryTable::getInstance()->getListActiveCategoryQueryNew($this->getId());
    }

    public function getListServiceByCategoryId()
    {
        return VtpServicesTable::getInstance()->getListServiceActiveQuery($this->getId());
    }
    
    public function getListChildByParetIdPt($portal)
    {
        return VtpCategoryTable::getInstance()->getListActiveCategoryQueryNewPt($this->getId(), $portal);
    }
}