<?php

/**
 * VtpMenuTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtpMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtpMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtpMenu');
    }

    public static function getMenuByType($type)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->select('name, parent_id, level, priority')
            ->where('type=?', $type)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority');
        $arrCat = $query->execute();
        $arrResult = array();
        $i18n = sfContext::getInstance()->getI18N();
        $arrResult[''] = '---' . $i18n->__('Chọn Menu cha') . '---';
        foreach ($arrCat as $cat) {
            $strTab = '';
            if ($cat->level > 0) {
                for ($i = 0; $i < $cat->level; $i++) {
                    $strTab = $strTab . '...';
                }
            }
            $arrResult[$cat->id] = $strTab . $cat->name;
        }

        return $arrResult;
    }

    public static function checkSlug($slug, $id)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->select('slug')
            ->where('slug=?', $slug)
            ->andWhere('id<>?', $id);
        return $query;
    }

    public static function getMenuById($id)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->select('level')
            ->Where('id=?', $id);
        return $query->fetchOne();
    }

    //Cập nhật thứ tự
    public static function updateOrder($categoryId, $parent_id, $level, $priority)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->update()
            ->set('parent_id', '?', $parent_id)
            ->set('level', '?', $level)
            ->set('priority', '?', $priority)
            ->where('id=?', $categoryId);
        return $query->execute();
    }

    public static function getAllMenu($type)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->where('type=?', $type)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->execute();
    }

    public static function getMenuByParentID($type, $parentId)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->where('type=?', $type)
            ->andWhere(($parentId != '') ? 'parent_id=?' : '(parent_id=? or parent_id is null)', $parentId)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->execute();
    }

    public static function getListMenu($type, $strCat)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->where('type=?', $type)
            ->andWhereIn('id', explode(',', $strCat))
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->execute();
    }

    //Lấy các category cùng mức
    public static function getMenuByLevel($type, $parentId)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->where('type=?', $type)
            ->andWhere(($parentId != '') ? 'parent_id=?' : '(parent_id=? or parent_id is null)', $parentId)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->execute();
    }

    public static function getMenuByPriority($type, $priority)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->where('type=?', $type)
            ->andWhere('priority > ?', $priority)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->execute();
    }

    /***
     * Begin method frontend
     */

    public static function getMenu($type)
    {
        $query = VtpMenuTable::getInstance()->createQuery()
            ->select('id, name, parent_id, level, link, slug')
            ->where('type=?', $type)
            ->andWhere('is_active=?', VtCommonEnum::NUMBER_ONE)
            ->andWhere('lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderby('priority asc');
        return $query->fetchArray();
    }


    //Lay parent theo slug
    public static function getListMenuBySlug($slug)
    {
        $query = VtpMenuTable::getInstance()->createQuery('c')
            ->select('p.id, p.name, p.description, p.image_path, p.parent_id, p.slug, p.link,c.type')
            ->innerJoin('c.ParentMenu p')
            ->where('c.slug=?', $slug)
            ->andWhere('p.lang=?', sfContext::getInstance()->getUser()->getCulture())
            ->orderBy('p.priority asc');
        return $query->fetchArray();
    }

    public static function getListVasService($slug)
    {

    }

    //Front end
}