generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           VtpProducts
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vtp_products
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        image_path: { label: Ảnh minh họa}
        product_code: { label: Mã phòng}
        product_name: { label: Tên phòng}
        price: { label: Giá theo tháng}
        price_promotion: { label: Giá theo ngày}
        priority: { label: Thứ tự hiển thị}
        link: { label: Đường dẫn}
        description: { label: Mô tả}
        content: { label: Nội dung}
        warranty_information: { label: Thông tin Bảo hành}
        manufacturer: { label: Hãng sản xuất}
        accessories: { label: Phụ kiện}
        is_active: { label: Trạng thái}
        is_home: { label: Trang chủ}
        is_hot: { label: phòng hot}
        category_id: { label: Căn}
        comment: {label: Đánh giá phòng}
        meta: {label: Nội dung thẻ Description}
        keywords: {label: Nội dung thẻ Keyword}
      list:
        title: Danh sách phòng
        display: [image_path, product_name, price, priority, link]
      filter:
       display: [product_name]
      form:
        class: vtManageProductsFormAdmin
        display: [product_name, category_id, image_path, price, price_promotion, link, description, content, meta, keywords, priority, is_hot, is_home, is_active]
        fields:
          product_name: { label: Tên phòng *}
          category_id: { label: Căn *}
      edit:
        title: Chỉnh sửa thông tin phòng
      new:
        title: Thêm mới thông tin phòng
