<?php

/**
 * sfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }
    
    public static function getListPermission()
    {
        $query=sfGuardPermissionTable::getInstance()->createQuery()
                ->select('id, name')
                ->where('types=?', VtCommonEnum::NUMBER_ONE)
                ->orderBy('name');
        return $query->execute();
    }
    public static function getListAllPermission()
    {
        $query=sfGuardPermissionTable::getInstance()->createQuery()
            ->select('id, name');
        return $query->execute();
    }
    public static function getPermissionByName($name)
    {
        $query=sfGuardPermissionTable::getInstance()->createQuery()
                ->select('id')
                ->where('name=?',$name);
        return $query->fetchOne();
    }
     
    public static function getUserPermissionCat($userId){
        $arrPer=sfGuardUserPermissionTable::getPermissionByUser($userId);
        $strPer='';
        foreach ($arrPer as $per)
        {
            $strPer .=$per->permission_id .',';
        }
         if ($strPer!=''){
            if(VtHelper::endsWith($strPer,',')){
                $strPer= substr($strPer, 0 ,strlen($strPer)-1);
            }
         }
         $query=sfGuardPermissionTable::getInstance()->createQuery()
                ->select('id')
                ->where('types=?',  VtCommonEnum::NUMBER_ONE)
                ->andWhereIn('id',  explode(',', $strPer));
         
         $strPer='';
         $arrPer=null;
         $arrPer=$query->execute();
         foreach ($arrPer as $per)
         {
             $strPer .=$per->id .',';
         }
         
         if ($strPer!=''){
            if(VtHelper::endsWith($strPer,',')){
                $strPer= substr($strPer, 0 ,strlen($strPer)-1);
            }
         }

//        var_dump($strPer);die;
         return $strPer;
    }
}