<?php

/**
 * PluginVtAdvertiseTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVtAdvertiseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   * @return object PluginVtAdvertiseTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginVtAdvertise');
  }

  /**
   * Ham tra ve truy van trong danh sach cua phan backend
   * Xu ly order by mac dinh theo nhieu truong
   * @author dongvt1
   * @created on 16/04/2013
   * @param dmDoctrineQuery $query
   * @return dmDoctrineQuery|Doctrine_Query
   */
  public function getAdminListQuery(dmDoctrineQuery $query)
  {
    $moduleName = 'vtAdvertise'; // Ten module trong admin su dung ham
    $query = parent::getAdminListQuery($query);
    $sort = sfContext::getInstance()->getUser()->getAttribute($moduleName . '.sort', null, 'admin_module');

    return (empty($sort[0]) || $sort[0] == 'created_at') ? $query->orderBy('created_at desc, id desc') : $query;
  }

  /**
   * Lay ra danh sach quang cao theo danh sach id
   * @author dongvt1
   * @created on 16/04/2013
   * @param $advIdArr mang danh sach ID cua quang cao
   */
  public function getAdvertiseList($advIdArr)
  {
    if (empty($advIdArr))
      return false;
    $result = $this->createQuery()
        ->where('is_active = ?', 1)
        ->andWhere('start_time <= ?', date('Y-m-d H:i:s', time()))
        ->andWhere('end_time >= ?', date('Y-m-d H:i:s', time()))
        ->andWhereIn('id', $advIdArr)
        ->orderBy('priority DESC, created_at DESC')
        ->execute();

    return $result;
  }
}