<?php

/**
 * PluginVtAdvertiseLocationItemTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVtAdvertiseLocationItemTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   * @return object PluginVtAdvertiseLocationItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginVtAdvertiseLocationItem');
  }

  /**
   * Tra ve danh sach advertise_id
   * @author dongvt1
   * @created on 18/04/2013
   */
  public function getAdvByLocationId($locationId)
  {

    $result = $this->createQuery()
        ->select('advertise_id')
        ->where('location_id = ?', $locationId)
        ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    if ($result) {
      return (is_array($result)) ? $result : array($result);
    }
    return $result;
  }
}