generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           AdFeedBack
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ad_feed_back
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: {label: "Họ tên"}
        email: {label: "Email"}
        title: {label: "Tiêu đề"}
        phone: {label: "SĐT"}
        message: {label: "Nội dung"}
        is_active: {label: "Trạng thái"}
      list:
        display: [title, name, phone, email, is_active]
        title: Danh sánh feedback
        object_actions:
          _edit: {label: Chi tiết}
          _delete: ~
      filter:
        display: [title, name, phone]
      form:
        display: [title, name, phone, email, message, is_active]
        class: ContractAdminForm
      edit:
        title: Chỉnh sửa feedback
      new:
        title: Thêm mới feedback
