<?php

/**
 * PluginVtSlideshowTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVtSlideshowTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginVtSlideshowTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginVtSlideshow');
  }

  /**
   * Tra ve truy van lay ra danh sach slideshow da kich hoat
   * @author dongvt1
   * @created on Jul 15-4-2013
   */
  public function getActivatedSlideshowQuery()
  {
    return $this->createQuery('a')
        ->where('a.is_active = 1')
        ->orderBy('a.priority DESC, a.id DESC');
  }

  /**
   * Tra ve danh sach slideshow da kich hoat
   * @author dongvt1
   * @created on Jul 15-4-2013
   * @param int $limit
   */
  public function getActivatedItems($limit = 5)
  {
    return $this->getActivatedSlideshowQuery()
        ->andWhere('start_time <= ?', date('Y-m-d H:i:s'))
        ->andWhere('end_time >= ?', date('Y-m-d H:i:s'))
        ->limit($limit)
        ->execute();
  }
}