## YAML Template.
---
indexSuccess:
  metas:
    title: Danh sách bài viết Đã duyệt
newSuccess:
  metas:
    title: Thêm mới bài viết Tin tức
editSuccess:
  metas:
    title: Chỉnh sửa bài viết tin tức